### ISSUE TITLE
Search field does not work

### ISSUE THREAD

**Issue by fkromer** [mendersoftware/mender-docs#122]
I recently recognized that the search field (top left corner of the [website](https://docs.mender.io/1.0/Getting-started)) does not work any more. No big deal... but I discovered the search very helpful :wink:

**Comment by estenberg** [comment]
Thanks for the report, we will look into this!

**Comment by estenberg** [comment]
Also for the future issues please note we are transitioning into JIRA as the bug tracker, it is available at: https://tracker.mender.io/projects/MEN. We will keep the current issues open here but if you have new ones please rather create them in JIRA.

**Comment by michaelatmender** [comment]
Hi @fkromer, thanks for letting us know. That's it fixed now!
