### ISSUE TITLE
Please add LICENSE

### ISSUE THREAD

**Issue by gmacario** [mendersoftware/mender-docs#174]
Unless you have different reasons I would suggest to pick a Green-light license for Documentation Artifacts as listed in <http://docs.projects.genivi.org/License/Public_Policy_for_GENIVI_Licensing_and_Copyright_v1.6.pdf>, such as:

* [Creative Commons Attribution-ShareAlike 4.0 License (CC-BY-SA)](http://creativecommons.org/licenses/by-sa/4.0)
* [Creative Commons Attribution 4.0 License (CC-BY) ](http://creativecommons.org/licenses/by/4.0)

**Comment by estenberg** [comment]
Hi @gmacario, thanks for the note. We are using Apache 2.0 in all other repositories, just curious why you do not consider this a Green-light license for docs at GENIVI?

**Comment by gmacario** [comment]
@estenberg 

> why you do not consider this a Green-light license for docs at GENIVI?

I Am Not A Lawyer(TM), however as far as I understood by reading the document above, GENIVI Legal Team considered Apache 2.0 good (green-lighted) for code artifacts but not particularly relevant for documentation.

See http://www.dreamsongs.com/IHE/IHE-50.html for some interesting thoughts on the subject.

**Comment by estenberg** [comment]
@gmacario thanks for reporting, we added the CC BY 4.0 license now: https://github.com/mendersoftware/mender-docs/blob/master/LICENSE
